### ISSUE TITLE
IP2CC not working on version 1.1.0

### ISSUE THREAD

**Issue by DarkCinema** [plarsson/com.globalcache#7] opened 2019-09-02 19:06 UTC
When sending the relay open or close commands and filling in a number in the "duration in miliseconds" box nothing happens op the ITACH IP2CC. while Homey is not giving an error.

I suspect that the IP2CC network stack is also crashing since the module IP stack is resetting and comming up with diffrent DHCP IP address. I have set the Itach to use a stratic address for now.

**Comment by plarsson** [comment] 2019-09-23 20:28
Hi, 

I've done some corrections as the duration arg was reserved by homey and therefor didn't populate. Also I've separated the duration card flow from the regular cc flow. However it should have worked anyway for you I think... Did it work correctly before version 1.1.0 ? Unfortunately I don't have any real cc device to test with.  

Do you have any chance to test directly from this source repo ? Otherwise I can arrange a new release.

**Comment by DarkCinema** [comment] 2019-10-14 13:43
Hi Plarsson,

Sorry for the dealy. I was not monitoring github..
I can test directly from this repo. So I should try to use the latest code?.
The version before 1.1.0 was working correct and switched the relays on the IP2CC.  Using the latest version posted for Homey does not switch the relays. For the duration i entered 0 and 10.000, but nothing happens.

**Comment by DarkCinema** [comment] 2019-10-17 18:01
I tested the latest build, stilll the IP2CC is not "relaying".  
I see that I have now two options when I add the devive in a flow. One without and one with the duration command. Note that if I select the one with the duration option I can not select the port and state,

If you need me to do some debugging, just ask.

PS> I installed version 1.0.1. and that version is working

**Comment by plarsson** [comment] 2019-10-22 15:12
Ok I will take another look. Its a bit tricky since I don't have the IP2CC device.

**Comment by migoman958** [comment] 2019-11-04 20:38
Older flows are working, the port is described as 1:3
in version 1.1.0 the port is described as "module 1 : port 1"
if I duplicate a flow and do not change Port it will continue to work!

So change the inputs to 1:1, 1:2 and 1:3!

**Comment by migoman958** [comment] 2019-11-04 20:43
Gissar att Larsson är svensk så tar det på svenska också:
I IP2IR fungerar det utmärkt med "module 1:port 1" men alltså inte i IP2CC
Tyvärr ingen logik i det:-)

Tack för att du tog upp tråden med GlobalCache appen!!!!!!

**Comment by plarsson** [comment] 2019-11-05 13:52
@migoman958 good finding, this is probably the root cause as you say.. I'll correct and push a fix soon.

**Comment by plarsson** [comment] 2019-11-06 09:52
Released a fix for this. Please try version 1.1.1

**Comment by migoman958** [comment] 2019-11-06 16:27
Now the "Send Relay Command" works fine. But "Send Relay Command With Duration" has no iTach connector to choose. the selection is empty.

The selection still looks like "module 1 : port 1" but it works!!

**Comment by plarsson** [comment] 2019-11-06 18:53
Ok thanks, thats good news. It looks like i missed some autocompletelisteners for the "Send Relay Command With Duration". I'll correct this

**Comment by plarsson** [comment] 2019-11-19 08:59
Hi @migoman958  can you try version 1.1.2 and see if "Send Relay Command With Duration" works now?

**Comment by migoman958** [comment] 2019-11-19 20:39
Now it works perfect! Thanks!!!

**Comment by plarsson** [comment] 2019-11-19 20:53
Thats good news! Thank you for testing.

**Closed as completed by plarsson** 2019-11-19 20:53 UTC
